#!/bin/bash
## Hostname, IP or FQDN.
HOST_NAME=127.0.0.1

## LDAP server configuration
## Comment these variables out if you already have a running ldap server.
## If SLAPD_DOMAIN and SLAPD_PASSWORD is set,
## LDAP_SERVER and LDAP_ACCOUNTBASE will be overwritten automatically.
SLAPD_DOMAIN=demo.com
SLAPD_PASSWORD=secret

## LDAP_SERVER and LDAP_ACCOUNTBASE become unnecessary
## if SLAPD_DOMAIN and SLAPD_PASSWORD are specified.
## LDAP Server IP or FQDN.
LDAP_SERVER=127.0.0.1
## LDAP account baseDN
LDAP_ACCOUNTBASE=ou=accounts,dc=demo,dc=com

## Gerrit administrator's uid in LDAP
GERRIT_ADMIN_UID=admin
GERRIT_ADMIN_PWD=password
GERRIT_ADMIN_EMAIL=admin@demo.com

REDMINE_ADMIN_USER=$GERRIT_ADMIN_UID
REDMINE_ADMIN_PASSWD=$GERRIT_ADMIN_PWD
## A Nexus server will be started by default.
## Specify this variable only if you want to use
## an existing nexus server instead.
## Jenkins uses NEXUS_WEBURL to setup maven repository mirror.
#NEXUS_WEBURL=http://127.0.0.1/nexus
